name: Rebase

on:
  schedule:
    - cron: '15 21 * * *'

jobs:
  build:
    name: Automatic rebase
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/MintOS-Revived/android_libcore.git
        cd android_libcore
        git fetch https://github.com/LineageOS/android_libcore.git lineage-17.1
        git rebase FETCH_HEAD
        git push -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
